### ISSUE TITLE
Trying to run with 24Gb VRAM

### ISSUE THREAD

**Issue by mxsage** [NVlabs/CALM#4]
Hi @tesslerc , thanks for the quick help on that other issue.
I'm trying to train on a 3090Ti, and wondering what are some good parameters to tweak in the config file (minibatch size, maybe?) to possibly train with this constraint. Any advice welcome! Including if it is even possible without major difference in results. Thanks.

**Comment by tesslerc** [comment]
I'd try the following:
1. https://github.com/NVlabs/CALM/blob/main/calm/data/cfg/humanoid_calm_sword_shield_getup.yaml Reduce number of envs. Try 2k.
2. https://github.com/NVlabs/CALM/blob/main/calm/data/cfg/train/rlg/calm_humanoid.yaml reduce minibatch size (8k for general and 2k for amp) and replay buffer sizes (50k).

**Comment by mxsage** [comment]
I was able to make it work with 20159MiB of VRAM using:

1024 environments
4096 minibatch_size
1024 amp_minibatch_size
50000 buffer sizes

If you think a different give-take will be more effective, I'm eager to hear!

It probably will be pretty slow to train (AMP base model was ~1 week as I remember). Are you able to share a rough estimate of how many GPU-hours it took to train the models described in the paper so I can do some estimates? Thank you for your time!

**Comment by mxsage** [comment]
I see. I was able to train the LLC enough so that the agent can successfully get up and emulate motions! So progress. However, I am getting an error when I try to run the precision training step, feeding in my just-trained LLC:

AttributeError: 'HumanoidHeadingConditioned' object has no attribute '_tar_motion_index'

Full output attached. Thanks for taking a look!
[precision-training-error.txt](https://github.com/NVlabs/CALM/files/11823794/precision-training-error.txt)

**Comment by tesslerc** [comment]
Thanks for testing and helping find these issues.
I have pushed a fix.
https://github.com/NVlabs/CALM/commit/283ff26cd84e540dfadf142064e9972716dfdf7c
The issue was a mismatch in variable names that occurred during public release.

**Comment by mxsage** [comment]
Hm, I'm still getting a similar error:
```
=> loading checkpoint 'output/Humanoid_22-14-39-36/nn/Humanoid.pth'
Loaded LLC checkpoint from output/Humanoid_22-14-39-36/nn/Humanoid.pth
Traceback (most recent call last):
  File "calm/run.py", line 274, in <module>
    main()
  File "calm/run.py", line 268, in main
    runner.run(vargs)
  File "/home/username/miniconda3/envs/rlgpu/lib/python3.7/site-packages/rl_games/torch_runner.py", line 139, in run
    self.run_train()
  File "/home/username/miniconda3/envs/rlgpu/lib/python3.7/site-packages/rl_games/torch_runner.py", line 125, in run_train
    agent.train()
  File "/home/username/dev/_CALM/calm/learning/common_agent.py", line 120, in train
    train_info = self.train_epoch()
  File "/home/username/dev/_CALM/calm/learning/common_agent.py", line 192, in train_epoch
    batch_dict = self.play_steps() 
  File "/home/username/dev/_CALM/calm/learning/hrl_agent.py", line 137, in play_steps
    self.obs, rewards, self.dones, infos = self.env_step(res_dict['actions'])
  File "/home/username/dev/_CALM/calm/learning/hrl_agent.py", line 81, in env_step
    curr_disc_reward = self._calc_disc_reward(amp_obs)
  File "/home/username/dev/_CALM/calm/learning/hrl_conditioned_agent.py", line 72, in _calc_disc_reward
    requested_motion_indices = self.vec_env.env.task.tar_locomotion_index.view(-1)
AttributeError: 'HumanoidHeadingConditioned' object has no attribute 'tar_locomotion_index'
```

Additionally, I opened a pull request fixing a few path-related issues. Thanks for taking a look!

**Comment by tesslerc** [comment]
Thank you. The pull request looks good.
Seems like there were some mistakes when cleaning up the repo for public upload. If you want to wait a few days, I'll get a local environment set up to make sure there aren't any other variable mismatch errors.

However, in the meantime it looks like "calm/learning/hrl_conditioned_agent.py", line 72" should be renamed from `requested_motion_indices = self.vec_env.env.task.tar_locomotion_index.view(-1)` to `requested_motion_indices = self.vec_env.env.task._tar_locomotion_index.view(-1)`. Essentially adding **_** which was missing.

**Comment by Robokan** [comment]
I have a dedicated 4090 with 24564Mib of memory and 

1024 environments
4096 minibatch_size
1024 amp_minibatch_size
50000 buffer sizes

doesn't work. I get:

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 6.26 GiB (GPU 0; 23.65 GiB total capacity; 13.02 GiB already allocated; 5.98 GiB free; 13.96 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Anyone how how to optimize the GPU memory to make this work?
